### ISSUE TITLE
Advantages

### ISSUE THREAD

**Issue by FranzSkuffka** [seaneking/poststylus#9]
What are the specific advantages of this, over, let's say, a gulp build chain that passes stylus output to postcss? Is this meant to be run on a production server

**Comment by seaneking** [comment]
Just meant to make things easier. Rather than using temp files or piping output from one task to another you can plug PostCSS into Stylus as a plugin, doing your PostCSS transforms as part of the Stylus compile. And yep can definitely be run in production (I do in all my work). At the end of the day though both result in the same thing, styles that have been run though both Stylus and PostCSS.

**Comment by FranzSkuffka** [comment]
So it's merely an API thing, coupling / pulling together the build pipeline of css from what I am gathering?
Thank you for the explanation.

**Comment by seaneking** [comment]
Yup, see https://github.com/seaneking/poststylus#passing-arguments-to-plugins
